python train.py mlp \
--dataset wenet \
--num_layers 3 \
--hidden_dim 16 \
--activation selu \
--optimizer adam \
--learning_rate 0.01 \
--repeats 10 \
--batch_norm True \
--epochs 100 \
--batch_size full $@
